
export const capitals = [
    "Abu Dhabi", "Abuja", "Accra", "Adamstown", "Addis Ababa", "Algiers", "Alofi", "Amman", "Amsterdam", 
    "Andorra la Vella", "Ankara", "Antananarivo", "Apia", "Ashgabat", "Asmara", "Astana", "Asunción", 
    "Athens", "Avarua", "Baghdad", "Baku", "Bamako", "Bandar Seri Begawan", "Bangkok", "Bangui", 
    "Banjul", "Basseterre", "Beijing", "Beirut", "Belgrade", "Belmopan", "Berlin", "Bern", "Bishkek", 
    "Bissau", "Bogotá", "Brasília", "Bratislava", "Brazzaville", "Bridgetown", "Brussels", "Bucharest", 
    "Budapest", "Buenos Aires", "Bujumbura", "Cairo", "Canberra", "Caracas", "Castries", "Cayenne", 
    "Charlotte Amalie", "Chisinau", "Cockburn Town", "Conakry", "Copenhagen", "Dakar", "Damascus", 
    "Dhaka", "Dili", "Djibouti", "Dodoma", "Doha", "Douglas", "Dublin", "Dushanbe", "Edinburgh", 
    "El Aaiún", "Episkopi Cantonment", "Freetown", "Funafuti", "Gaborone", "George Town", "Georgetown", 
    "Gibraltar", "Gitega", "Guatemala City", "Gustavia", "Hagåtña", "Hamilton", "Hanga Roa", "Hanoi", 
    "Harare", "Hargeisa", "Havana", "Helsinki", "Honiara", "Islamabad", "Jakarta", "Jamestown", 
    "Jerusalem", "Juba", "Kabul", "Kampala", "Kathmandu", "Khartoum", "Kiev", "Kigali", "King Edward Point", 
    "Kingston", "Kingstown", "Kinshasa", "Kuala Lumpur", "Kuwait City", "Libreville", "Lilongwe", 
    "Lima", "Lisbon", "Ljubljana", "Lomé", "London", "Luanda", "Lusaka", "Luxembourg", "Madrid", "Majuro", 
    "Malabo", "Malé", "Managua", "Manama", "Manila", "Maputo", "Marigot", "Maseru", "Mata-Utu", "Mbabane", 
    "Melekeok", "Mexico City", "Minsk", "Mogadishu", "Monaco", "Monrovia", "Montevideo", "Moroni", "Moscow", 
    "Muscat", "N'Djamena", "Nairobi", "Nassau", "Naypyidaw", "New Delhi", "Ngerulmud", "Niamey", "Nicosia", 
    "Nouakchott", "Nouméa", "Nuku'alofa", "Nuuk", "Oranjestad", "Oslo", "Ottawa", "Ouagadougou", "Pago Pago", 
    "Palikir", "Panama City", "Papeete", "Paramaribo", "Paris", "Philipsburg", "Phnom Penh", "Plymouth", 
    "Podgorica", "Port-au-Prince", "Port Louis", "Port Moresby", "Port of Spain", "Port Vila", "Porto-Novo", 
    "Prague", "Praia", "Pretoria", "Pristina", "Pyongyang", "Quito", "Rabat", "Ramallah", "Reykjavík", 
    "Riga", "Riyadh", "Road Town", "Rome", "Roseau", "Saipan", "San José", "San Juan", "San Marino", 
    "San Salvador", "Sana'a", "Santiago", "Santo Domingo", "São Tomé", "Sarajevo", "Seoul", "Singapore", 
    "Skopje", "Sofia", "Sri Jayawardenepura Kotte", "St. George's", "St. Helier", "St. John's", "St. Peter Port", 
    "St. Pierre", "Stanley", "Stepanakert", "Stockholm", "Sucre", "Sukhumi", "Suva", "Taipei", "Tallinn", 
    "Tarawa", "Tashkent", "Tbilisi", "Tegucigalpa", "Tehran", "Thimphu", "Tirana", "Tiraspol", "Tokyo", 
    "Tórshavn", "Tripoli", "Tskhinvali", "Tunis", "Ulaanbaatar", "Vaduz", "Valletta", "The Valley", 
    "Vatican City", "Victoria", "Vienna", "Vientiane", "Vilnius", "Wellington", "West Island", "Willemstad", 
    "Windhoek", "Yamoussoukro", "Yaoundé", "Yaren", "Yerevan", "Zagreb"
];
