export const capitals = [
    "Abu Dhabi", "Abou Dabi", "Abuja", "Accra", "Adamstown", "Addis Ababa", "Addis-Abeba", "Algiers", "Alger", "Alofi", "Amman", "Amsterdam", 
    "Andorra la Vella", "Andorre-la-Vieille", "Ankara", "Antananarivo", "Apia", "Ashgabat", "Achgabat", "Asmara", "Astana", "Asunción", 
    "Athens", "Athènes", "Avarua", "Baghdad", "Bagdad", "Baku", "Bakou", "Bamako", "Bandar Seri Begawan", "Bangkok", "Bangui", 
    "Banjul", "Basseterre", "Beijing", "Pékin", "Beirut", "Beyrouth", "Belgrade", "Belmopan", "Berlin", "Bern", "Berne", "Bishkek", 
    "Bichkek", "Bissau", "Bogotá", "Bogota", "Brasília", "Brasilia", "Bratislava", "Brazzaville", "Bridgetown", "Brussels", "Bruxelles", "Bucharest", "Bucarest", 
    "Budapest", "Buenos Aires", "Bujumbura", "Cairo", "Le Caire", "Canberra", "Caracas", "Castries", "Cayenne", 
    "Charlotte Amalie", "Chisinau", "Chişinău", "Cockburn Town", "Conakry", "Copenhagen", "Copenhague", "Dakar", "Damascus", "Damas", 
    "Dhaka", "Dacca", "Dili", "Djibouti", "Dodoma", "Doha", "Douglas", "Dublin", "Dushanbe", "Douchanbe", "Edinburgh", "Édimbourg", 
    "El Aaiún", "Episkopi Cantonment", "Freetown", "Funafuti", "Gaborone", "George Town", "Georgetown", 
    "Gibraltar", "Gitega", "Guatemala City", "Guatemala", "Gustavia", "Hagåtña", "Hamilton", "Hanga Roa", "Hanoi", "Hanoï", 
    "Harare", "Hargeisa", "Havana", "La Havane", "Helsinki", "Honiara", "Islamabad", "Jakarta", "Jamestown", 
    "Jerusalem", "Jérusalem", "Juba", "Kabul", "Kaboul", "Kampala", "Kathmandu", "Katmandou", "Khartoum", "Kiev", "Kyiv", "Kigali", "King Edward Point", 
    "Kingston", "Kingstown", "Kinshasa", "Kuala Lumpur", "Kuwait City", "Koweït", "Libreville", "Lilongwe", 
    "Lima", "Lisbon", "Lisbonne", "Ljubljana", "Lomé", "London", "Londres", "Luanda", "Lusaka", "Luxembourg", "Madrid", "Majuro", 
    "Malabo", "Malé", "Managua", "Manama", "Manila", "Manille", "Maputo", "Marigot", "Maseru", "Mata-Utu", "Mbabane", 
    "Melekeok", "Mexico City", "Mexico", "Minsk", "Mogadishu", "Mogadiscio", "Monaco", "Monrovia", "Montevideo", "Moroni", "Moscow", "Moscou", 
    "Muscat", "Mascate", "N'Djamena", "Nairobi", "Nassau", "Naypyidaw", "New Delhi", "Ngerulmud", "Niamey", "Nicosia", "Nicosie", 
    "Nouakchott", "Nouméa", "Nuku'alofa", "Nuuk", "Oranjestad", "Oslo", "Ottawa", "Ouagadougou", "Pago Pago", 
    "Palikir", "Panama City", "Panama", "Papeete", "Paramaribo", "Paris", "Philipsburg", "Phnom Penh", "Plymouth", 
    "Podgorica", "Port-au-Prince", "Port Louis", "Port Moresby", "Port of Spain", "Port d'Espagne", "Port Vila", "Porto-Novo", 
    "Prague", "Praia", "Pretoria", "Pristina", "Pyongyang", "Quito", "Rabat", "Ramallah", "Reykjavík", "Reykjavik", 
    "Riga", "Riyadh", "Riyad", "Road Town", "Rome", "Roma", "Roseau", "Saipan", "San José", "San Juan", "San Marino", "Saint-Marin", 
    "San Salvador", "Sana'a", "Santiago", "Santo Domingo", "Saint-Domingue", "São Tomé", "Sao Tome", "Sarajevo", "Seoul", "Séoul", "Singapore", "Singapour", 
    "Skopje", "Sofia", "Sri Jayawardenepura Kotte", "St. George's", "St. Helier", "St. John's", "St. Peter Port", 
    "St. Pierre", "Stanley", "Stepanakert", "Stockholm", "Sucre", "Sukhumi", "Suva", "Taipei", "Taïpei", "Tallinn", 
    "Tarawa", "Tashkent", "Tachkent", "Tbilisi", "Tbilissi", "Tegucigalpa", "Tehran", "Téhéran", "Thimphu", "Tirana", "Tiraspol", "Tokyo", "Honiara", 
    "Tórshavn", "Tripoli", "Tskhinvali", "Tunis", "Ulaanbaatar", "Oulan-Bator", "Vaduz", "Valletta", "La Valette", "The Valley", 
    "Vatican City", "Vatican", "Victoria", "Vienna", "Vienne", "Vientiane", "Vilnius", "Wellington", "West Island", "Willemstad", 
    "Windhoek", "Yamoussoukro", "Yaoundé", "Yaren", "Yerevan", "Erevan", "Zagreb", "Warsaw", "Varsovie"
];
